import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from "@/app/components/ui/ThemeContext"
import ModeToggle from './page'
import Providers from '@/app/components/provider'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',

}
export const viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: 'white' },
    { media: '(prefers-color-scheme: dark)', color: 'black' },
  ],
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   
    <html lang="en" suppressHydrationWarning>
       
       <head />
      <body className={inter.className} >
      <Providers>
     <ThemeProvider>
        {children}
        </ThemeProvider>
        </Providers>
      </body>
      
     
    </html>
  
  )
}
